import { Router } from 'express';
import { authRouter } from './auth.routes.js';
import { expertChatRouter } from '../chat/routes/expertChatRoutes.js';
import { complaintRouter } from './complaint.routes.js';
import { communityRouter } from './community.routes.js';
import { communityRoutes as communityFeedRoutes } from '../community/community.routes.js';
import { consumerMarketplaceRouter } from './consumer-marketplace.routes.js';
import { cartRouter } from './cart.routes.js';
import { farmerMarketplaceRouter } from './farmer-marketplace.routes.js';
import { grievanceRouter } from './grievance.routes.js';
import { marketRouter } from './market.routes.js';
import { marketplaceRouter } from '../modules/marketplace/marketplace.routes.js';
import { orderRouter } from './order.routes.js';
import { paymentRouter } from './payment.routes.js';
import { chatbotRouter } from '../modules/chatbot/chatbot.routes.js';
import { farmerPaymentsRouter } from './farmer-payments.routes.js';
import { schemeRouter } from './scheme.routes.js';
import { talukAdminRouter } from './taluk-admin.routes.js';
import { usersRouter } from './users.routes.js';
import { voiceRouter } from './voiceRoutes.js';
import { voiceRouter as voiceParseRouter } from './voice.routes.js';
import { cropPricingRouter } from '../modules/crop-pricing/crop-pricing.routes.js';
import { whatsappRouter } from './whatsapp.routes.js';

const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/farmer', farmerMarketplaceRouter);
apiRouter.use('/marketplace', marketplaceRouter);
apiRouter.use('/marketplace', consumerMarketplaceRouter);
apiRouter.use('/marketplace', marketRouter);
apiRouter.use('/cart', cartRouter);
apiRouter.use('/orders', orderRouter);
apiRouter.use('/payments', paymentRouter);
apiRouter.use('/farmer/payments', farmerPaymentsRouter);
apiRouter.use('/community', communityFeedRoutes);
apiRouter.use('/community', communityRouter);
apiRouter.use('/schemes', schemeRouter);
apiRouter.use('/grievances', grievanceRouter);
apiRouter.use('/', complaintRouter);
apiRouter.use('/chatbot', chatbotRouter);
apiRouter.use('/expert-chat', expertChatRouter);
apiRouter.use('/admin/taluk-admin', talukAdminRouter);
apiRouter.use('/voice', voiceRouter);
apiRouter.use('/voice', voiceParseRouter);
apiRouter.use('/', cropPricingRouter);
apiRouter.use('/whatsapp', whatsappRouter);

export { apiRouter };
